-- Insert email template settings
INSERT INTO platform_settings (setting_key, setting_value)
VALUES ('email_templates', '{
  "signup_confirmation": {
    "subject": "Welcome to DolphySN - Verify Your Email",
    "body": "<div style=\"font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;\">\n  <div style=\"background: linear-gradient(135deg, #1c76e6 0%, #3b82f6 100%); padding: 30px; text-align: center; border-radius: 10px 10px 0 0;\">\n    <h1 style=\"color: white; margin: 0;\">Welcome to DolphySN!</h1>\n  </div>\n  <div style=\"background: #f9fafb; padding: 30px; border-radius: 0 0 10px 10px;\">\n    <h2 style=\"color: #1f2937; margin-top: 0;\">Verify Your Email Address</h2>\n    <p style=\"color: #4b5563; font-size: 16px;\">Hello {{name}},</p>\n    <p style=\"color: #4b5563; font-size: 16px;\">Thank you for joining DolphySN! Please click the button below to verify your email address and complete your registration.</p>\n    <div style=\"text-align: center; margin: 30px 0;\">\n      <a href=\"{{confirmation_link}}\" style=\"background: linear-gradient(135deg, #1c76e6 0%, #3b82f6 100%); color: white; padding: 15px 30px; text-decoration: none; border-radius: 8px; font-weight: bold; display: inline-block;\">Verify Email Address</a>\n    </div>\n    <p style=\"color: #6b7280; font-size: 14px;\">If the button does not work, copy and paste this link into your browser:</p>\n    <p style=\"color: #1c76e6; font-size: 14px; word-break: break-all;\">{{confirmation_link}}</p>\n    <p style=\"color: #6b7280; font-size: 14px;\">This link expires in 24 hours.</p>\n    <hr style=\"border: none; border-top: 1px solid #e5e7eb; margin: 20px 0;\" />\n    <p style=\"color: #9ca3af; font-size: 12px; text-align: center;\">If you did not create an account, please ignore this email.</p>\n  </div>\n</div>"
  },
  "forgot_password": {
    "subject": "DolphySN - Password Reset Code",
    "body": "<div style=\"font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;\">\n  <div style=\"background: linear-gradient(135deg, #1c76e6 0%, #3b82f6 100%); padding: 30px; text-align: center; border-radius: 10px 10px 0 0;\">\n    <h1 style=\"color: white; margin: 0;\">DolphySN</h1>\n  </div>\n  <div style=\"background: #f9fafb; padding: 30px; border-radius: 0 0 10px 10px;\">\n    <h2 style=\"color: #1f2937; margin-top: 0;\">Password Reset Code</h2>\n    <p style=\"color: #4b5563; font-size: 16px;\">You requested to reset your password. Use the code below to verify your identity:</p>\n    <div style=\"background: white; border: 2px dashed #1c76e6; border-radius: 10px; padding: 20px; text-align: center; margin: 20px 0;\">\n      <span style=\"font-size: 32px; font-weight: bold; letter-spacing: 8px; color: #1c76e6;\">{{code}}</span>\n    </div>\n    <p style=\"color: #6b7280; font-size: 14px;\">This code expires in 10 minutes. If you did not request this, please ignore this email.</p>\n  </div>\n</div>"
  }
}'::jsonb)
ON CONFLICT (setting_key) DO UPDATE SET setting_value = EXCLUDED.setting_value;